services:
  php:
    image: php-service
    build: .
    ports:
      - 8080:80
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_DATABASE=memy

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=memy
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/0_init.sql